package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            param("AzAppId", "767d5e60-4d25-4794-9a4d-f714fab829e0")
        }
        update {
            param("AzAppId", "949717e5-4c7e-4c3d-bf28-534dc99aa45b")
        }
        expect {
            password("AzPassword", "credentialsJSON:b66a8739-aa0b-4987-a245-07c6907bdd01", label = "AzPassword")
        }
        update {
            password("AzPassword", "credentialsJSON:ea1558cd-1d4f-4a20-b833-b1d794d56246", label = "AzPassword")
        }
        expect {
            password("OctoApiKey", "credentialsJSON:959b363e-7a9f-4706-86fa-532f285020e7", label = "OctoApiKey")
        }
        update {
            password("OctoApiKey", "credentialsJSON:111569ae-279e-4a0c-8211-67b8b4f8fc41", label = "OctoApiKey")
        }
        expect {
            param("OctoProject", "teamcity-dotnet-7-container-apps")
        }
        update {
            param("OctoProject", "Onion Architecture DotNet 7 Container Apps")
        }
        expect {
            param("OctoSpace", "Spaces-195")
        }
        update {
            param("OctoSpace", "Spaces-83")
        }
    }
}
